const teammates = [
    {
        full_name: "Emmanuel Monsalve Parra",
        rol: "Lider de Desarrollo",
        instagram: "https://www.instagram.com/emmusmp/",
        linkedin: "https://www.linkedin.com/in/emmanuelmonsalve/",
        twitter: "https://x.com/emmusmp",
        github: "https://github.com/MachinEmmus",
    },
    {
        full_name: "Juan Camilo Gonzalez Hoyos",
        rol: "Desarrollador Jr.",
        instagram: null,
        linkedin: "https://www.linkedin.com/in/juan-camilo-gonzalez-hoyos/",
        twitter: null,
        github: "https://github.com/ZeikoDev",
    },
    {
        full_name: "Santiago Lopez Vallejo",
        rol: "Desarrollador Full Stack Jr.",
        instagram: null,
        linkedin: "https://www.linkedin.com/in/santyago43/",
        twitter: null,
        github: "https://github.com/ZeikoDev",
    },
    {
        full_name: "Maicol Arroyave Alvarez",
        rol: "Desarrollador Full Stack Semi-Senior",
        instagram: "https://www.instagram.com/maicol.arroyave.9/",
        linkedin: "https://www.linkedin.com/in/maicolaa/",
        twitter: null,
        github: "https://github.com/MaicolAA",
    },
    {
        full_name: "Yeison Andrés Garzon Toro",
        rol: "Desarrollador de Software Senior",
        instagram: "https://www.instagram.com/yeison.js",
        linkedin: "https://www.linkedin.com/in/yeison-toro",
        twitter: null,
        github: "https://github.com/devyeisont",
    },
    {
        full_name: "Juan Pablo Deossa",
        rol: "Desarrollador Frontend",
        instagram: null,
        linkedin: "https://www.linkedin.com/in/juan-pablo-deossa-ramirez-1b252424b/",
        twitter: null,
        github: "https://github.com/JuanPabloDeossa",
    },
    {
        full_name: "Alexander Rendón londoño",
        rol: "Lider de Desarrollo",
        instagram: null,
        linkedin: "https://www.linkedin.com/in/alex-rl",
        twitter: null,
        github: "https://github.com/AlexRL-12",
    },
    {
        full_name: "Erick Fragoso",
        rol: "Lider de Diseño",
        instagram: "https://www.instagram.com/erickfragoso.design/",
        linkedin: "https://www.linkedin.com/in/erick-fragoso-905067229/",
        twitter: null,
        github: "https://github.com/erickfrago",
    },
];
