/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/JzBboVgWlzB
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function Component() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48 bg-primary">
        <div className="container px-4 md:px-6">
          <div
            className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <h1
                  className="text-3xl font-bold tracking-tighter text-primary-foreground sm:text-5xl xl:text-6xl/none">
                  Acme Design Co.
                </h1>
                <p className="max-w-[600px] text-primary-foreground md:text-xl">
                  We are a team of experienced designers and developers specializing in creating beautiful and
                  functional websites and applications.
                </p>
              </div>
            </div>
            <img
              src="/placeholder.svg"
              width="550"
              height="400"
              alt="Hero"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last" />
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="space-y-4 text-center">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Meet the Team</h2>
            <p className="max-w-[600px] mx-auto text-muted-foreground md:text-xl">
              Our talented team of designers and developers are dedicated to delivering exceptional results for our
              clients.
            </p>
          </div>
          <div
            className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 mt-8">
            <div className="bg-card rounded-lg overflow-hidden">
              <img
                src="/placeholder.svg"
                width="400"
                height="400"
                alt="Team Member"
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "400/400", objectFit: "cover" }} />
              <div className="p-4">
                <h3 className="text-lg font-semibold">John Doe</h3>
                <p className="text-muted-foreground">Lead Designer</p>
              </div>
            </div>
            <div className="bg-card rounded-lg overflow-hidden">
              <img
                src="/placeholder.svg"
                width="400"
                height="400"
                alt="Team Member"
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "400/400", objectFit: "cover" }} />
              <div className="p-4">
                <h3 className="text-lg font-semibold">Jane Smith</h3>
                <p className="text-muted-foreground">Frontend Developer</p>
              </div>
            </div>
            <div className="bg-card rounded-lg overflow-hidden">
              <img
                src="/placeholder.svg"
                width="400"
                height="400"
                alt="Team Member"
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "400/400", objectFit: "cover" }} />
              <div className="p-4">
                <h3 className="text-lg font-semibold">Michael Johnson</h3>
                <p className="text-muted-foreground">Backend Developer</p>
              </div>
            </div>
            <div className="bg-card rounded-lg overflow-hidden">
              <img
                src="/placeholder.svg"
                width="400"
                height="400"
                alt="Team Member"
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "400/400", objectFit: "cover" }} />
              <div className="p-4">
                <h3 className="text-lg font-semibold">Emily Davis</h3>
                <p className="text-muted-foreground">UI/UX Designer</p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
        <div className="container px-4 md:px-6">
          <div className="space-y-4 text-center">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Our Past Projects</h2>
            <p className="max-w-[600px] mx-auto text-muted-foreground md:text-xl">
              Check out some of the amazing projects we've worked on for our clients.
            </p>
          </div>
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 mt-8">
            <div className="bg-card rounded-lg overflow-hidden">
              <img
                src="/placeholder.svg"
                width="400"
                height="300"
                alt="Project 1"
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "400/300", objectFit: "cover" }} />
              <div className="p-4">
                <h3 className="text-lg font-semibold">Project 1</h3>
                <p className="text-muted-foreground">A modern and responsive website for a leading tech company.</p>
              </div>
            </div>
            <div className="bg-card rounded-lg overflow-hidden">
              <img
                src="/placeholder.svg"
                width="400"
                height="300"
                alt="Project 2"
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "400/300", objectFit: "cover" }} />
              <div className="p-4">
                <h3 className="text-lg font-semibold">Project 2</h3>
                <p className="text-muted-foreground">A custom e-commerce platform for a small business.</p>
              </div>
            </div>
            <div className="bg-card rounded-lg overflow-hidden">
              <img
                src="/placeholder.svg"
                width="400"
                height="300"
                alt="Project 3"
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "400/300", objectFit: "cover" }} />
              <div className="p-4">
                <h3 className="text-lg font-semibold">Project 3</h3>
                <p className="text-muted-foreground">
                  A sleek and modern web application for a non-profit organization.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="space-y-4 text-center">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Get in Touch</h2>
            <p className="max-w-[600px] mx-auto text-muted-foreground md:text-xl">
              Have a project in mind? Fill out the form below and we'll get back to you as soon as possible.
            </p>
          </div>
          <form className="max-w-md mx-auto mt-8 space-y-4">
            <Input type="text" placeholder="Name" className="w-full" />
            <Input type="email" placeholder="Email" className="w-full" />
            <Textarea placeholder="Message" className="w-full" />
            <Button type="submit" className="w-full">
              Submit
            </Button>
          </form>
        </div>
      </section>
      <footer
        className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 Acme Design Co. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link
            href="#"
            className="text-xs hover:underline underline-offset-4"
            prefetch={false}>
            Terms of Service
          </Link>
          <Link
            href="#"
            className="text-xs hover:underline underline-offset-4"
            prefetch={false}>
            Privacy
          </Link>
        </nav>
      </footer>
    </div>)
  );
}
